core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("datadoc.urls", "datadoc"), namespace="datadoc")),
]

datadoc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.explore, name="home"),
    path("explore/", views.explore, name="explore"),
    path("upload-url/", views.upload_url, name="upload_url"),
    path("upload-file/", views.upload_file, name="upload_file"),
    path("edit-form/", views.edit_form, name="edit_form"),
    path("datatable/", views.datatable, name="datatable"),
    path("datatable-schema", views.datatable_schema, name="datatable_schema"),
    # non template paths
    path("download/<str:filename>/", views.download_template, name="download_template"),
    path("upload/file/", views.upload_files, name="upload_files"),
    path("upload/url/", views.upload_file_url, name="upload_file_url"),
    path("process-csv/", views.process_csv, name="process_csv"),
    path('get-prefixes/', views.get_prefixes_view, name='get_prefixes'),
]

datadoc/models.py
from django.db import models

# Create your models here.

datadoc/views.py
"""Implement the views functions"""

from pathlib import Path
import mimetypes

from django.conf import settings
from django.apps import apps
from django.shortcuts import render
from django.http import FileResponse, Http404, JsonResponse, HttpRequest
from django.views.decorators.csrf import csrf_exempt

from tripper.datadoc.dataset import get_prefixes
from .utils import (
    json_response,
    get_triplestore,
    handle_file,
    handle_file_url,
    process_csv_form,
    get_setting,
    triplestore_search,
    triplestore_filters,
    update_user_filter
)


def default_context(request: HttpRequest):
    """ Create a default context from the settings and from multiple
        AppConfig.
    """
    ctx = {}
    base = get_setting('base_template', 'datadoc/base.html')
    ctx['datadoc_base_template'] = base
    app_names = get_setting('apps', [])
    for app in apps.get_app_configs():
        if app.name in app_names:
            app.update_context(request, ctx)
    if settings.DEBUG:
        usr = get_setting('fake_user', None)
        if isinstance(usr, dict):
            ctx['user'] = usr
    return ctx


def index(request: HttpRequest):
    ctx = default_context(request)
    ctx['hide_header'] = True
    return render(request, "datadoc/index.html", ctx)


def home(request: HttpRequest):
    ctx = default_context(request)
    return render(request, "datadoc/views/home.html", ctx)


def edit_form(request: HttpRequest):
    prefix = get_setting('prefix', {})
    prefix_list = []
    for key, val in prefix.items():
        prefix_list.append({'prefix': key, 'iri': val})
    ctx = default_context(request)
    ctx.update(prefix_list=prefix_list)
    return render(request, "datadoc/views/edit_form.html", context=ctx)


def get_prefixes_view(request: HttpRequest):
    """
    Django view to return the list of prefixes from Tripper as JSON.
    """
    prefixes_dict = get_prefixes()
    prefixes = [{'prefix': k, 'iri': v} for k, v in prefixes_dict.items()]
    return JsonResponse({'prefixes': prefixes})


def upload_file(request: HttpRequest):
    ctx = default_context(request)
    return render(request, "datadoc/views/upload_file.html", ctx)


def upload_url(request: HttpRequest):
    ctx = default_context(request)
    return render(request, "datadoc/views/upload_url.html", ctx)


def explore(request: HttpRequest):
    """ Search in triple store """
    ctx = default_context(request)

    if request.method == 'GET':
        # get the query
        ctx['query'] = request.GET.dict()

        # fetch the filters and update the context
        triplestore_filters(ctx, request.user)

        ctx['error'] = ''
        rdf_type = ctx['search']['rdf_type']
        criterias = ctx['search']['criterias']
        if rdf_type or criterias:
            try:
                p = request.GET.get('page', '1')
                s = request.GET.get('size', '10')
                result = triplestore_search(rdf_type, criterias, p, s)
                if result:
                    ctx.update(result)
            except Exception as ex:
                doc = ex.__class__.__doc__
                if not doc:
                    doc = ex.__class__.__name__
                err = str(ex).strip("'")
                ctx['error'] = f'{doc.rstrip(".")}: "{err}".'

        return render(request, "datadoc/views/explore.html", ctx)

    elif request.method == 'POST':
        name = request.POST.get('name', '')
        criteria = request.POST.get('criteria', '')
        choices = update_user_filter(ctx, request.user, criteria, 'POST')
        data = {'name': name, 'choices': choices}
        return JsonResponse(data)

    elif request.method == 'DELETE':
        data = {'status': 'nothing to delete'}
        criteria = request.GET.get('criteria', '')
        if criteria:
            update_user_filter(ctx, request.user, criteria, 'DELETE')
            data = {'status': 'deleted'}
        return JsonResponse(data)


def download_template(request, filename):
    """Download a template file"""
    file_templates = get_setting('file_templates', None)
    if isinstance(file_templates, Path):
        template_path = file_templates / filename
        if template_path.exists():
            mime_type, _ = mimetypes.guess_type(template_path)
            return FileResponse(
                open(template_path, "rb"),
                content_type=mime_type,
                as_attachment=True,
                filename=filename,
            )
    raise Http404("Template not found")


def upload_files(request):
    """Upload files to the triple store"""

    if request.method != "POST" or "files" not in request.FILES:
        return json_response("Error", "No file uploaded")

    ts = get_triplestore()
    return handle_file(request.FILES["files"], ts)


def upload_file_url(request):
    """Upload documentation to the triple store from file URL's"""
    if request.method == "POST":
        url = request.POST.get("url")
        ts = get_triplestore()
        return handle_file_url(url, ts)


@csrf_exempt
def process_csv(request):
    if request.method == "POST":

        ts = get_triplestore()

        csv_prefix = request.POST.get("csv_prefix")
        if csv_prefix:
            for line in csv_prefix.splitlines():
                kv = line.split(':', 1)
                if len(kv) == 2:
                    pr, ns = kv
                    if pr and ns:
                        ts.bind(pr, ns)

        csv_data = request.POST.get("csv_data")
        return process_csv_form(csv_data, ts)

datadoc/templates/datadoc/components/dialog.html
<div id="dialog" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p id="dialog-message"></p>
        <p id="dialog-status"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% block scripts %}
<script>
  function showDialog(message, status_code) {
    $('#dialog .modal-title').text(status_code == 200 ? 'Success' : 'Error');
    $('#dialog-message').text(message);
    $('#dialog-status').text(`Status Code: ${status_code}`);
    $('#dialog').modal('show');
  }
</script>
{% endblock %}

datadoc/templates/datadoc/components/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Twelfth navbar example">
  <div class="container-fluid">
    <button class="navbar-toggler collapsed" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse justify-content-md-center collapse" id="navbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" id="menu-home"
             href="{% url 'datadoc:index' %}">
            <i class="bi bi-house"></i> datadocweb</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'datadoc:explore' %}" id="menu-explore">
            <i class="bi bi-search"></i> Explore</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu-upload"
             data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-cloud-arrow-up"></i> Upload</a>
          <ul class="dropdown-menu" aria-labelledby="menu-upload">
            <li><a class="dropdown-item" href="{% url 'datadoc:upload_url' %}">
                Upload via URL
            </a></li>
            <li><a class="dropdown-item" href="{% url 'datadoc:upload_file' %}">
              Upload File
            </a></li>
            <li><a class="dropdown-item" href="{% url 'datadoc:edit_form' %}">
              Edit Form
            </a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">
            <i class="bi bi-question-circle"></i> About</a>
        </li>    
      </ul>
    </div>
  </div>
</nav>

datadoc/templates/datadoc/index.html
{% extends datadoc_base_template %}

{% block content %}
<div class="d-flex text-center align-items-center min-vh-100">
  <div class="container-fluid">
  <div class="px-4 py-5 my-5 text-center">
    <a href="https://github.com/EMMC-ASBL/datadocweb" target="_blank"
       class="text-decoration-none">
      <h1 style="background: -webkit-linear-gradient(#eee, #333); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
        datadocweb
      </h1>
    </a>
    <h1 class="display-5 fw-bold">Data Documentation Web Tools</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">
        Web graphical user interface for data documentation using
        <a href="https://github.com/EMMC-ASBL/tripper" target="_blank">
          tripper</a>.
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a class="btn btn-outline-secondary btn-lg px-4"
           href="https://github.com/EMMC-ASBL/datadocweb"
           role="button" target="_blank">
          Read more on datadocweb
        </a>
        <a class="btn btn-primary btn-lg px-4 gap-3"
           href="{% url 'datadoc:home' %}" role="button">
          Open App
        </a>        
      </div>
    </div>
  </div>
  </div>
</div>
{% endblock %}

datadoc/templates/datadoc/partials/dropzone.html
<form action="{% url 'datadoc:upload_files' %}" class="dropzone mb-3" id="files-dropzone">
  {% csrf_token %}
</form>

<div class="alert alert-info" role="alert">
  For Excel files, only worksheets where cell A1 contains <strong>@id</strong>
  will be uploaded. The first row must define the column headers, and headers
  must not end with a number (e.g. <strong>@type.1</strong> is not allowed).
</div>

<div id="results">

</div>

<div id="upload-result" style="display: none;">
<div class="alert alert-{color} alert-dismissible fade show" role="alert" id="file-{uuid}">
  <strong>{status}</strong> for file "{file}": {message}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
</div>

{% block scripts %}
<script>

function formatString(template, values) {
  return template.replace(/{(\w+)}/g, (_, key) => values[key] ?? `{${key}}`);
}

function getAndReplace(htmlId, values, appendTo) {
  let html = $(htmlId).html();
  let newhtml = formatString(html, values);
  if (appendTo) {
    $(appendTo).append(newhtml);
  }
  return newhtml;
}

function showUploadResult(response, file) {
  console.log(file.name);
  console.log(response);

  let values = {
    status: 'Error',
    color: 'danger',
    file: file.name,
    uuid: file.upload.uuid,
    message: response.message
  };
  if (response.status_code == 200) {
    values.status = 'Success';
    values.color = 'success';
  }
  if (Array.isArray(response.message)) {
    let msg = '';
    let ul = '';
    response.message.forEach(item => {
      if (item.startsWith('- ')) {
        ul += `<li>${item.substring(2)}</li>`;
      } else {
        msg += item;
      }
    });
    values.message = ul ? `${msg}<ul>${ul}</ul>` : msg;
  }

  getAndReplace('#upload-result', values, '#results');

  if (response.status_code == 200) {
    var fid = `#file-${file.upload.uuid}`;
    window.setTimeout(() => { $(fid).remove(); }, 10000);
  }
}

Dropzone.options.filesDropzone = {
  paramName: "files",
  maxFilesize: 10, // MB
  timeout: 1800000, // 30 minutes,
  acceptedFiles: '.xlsx,.csv,.json,.yaml',
  init: function() {
    this.on("success", (file, response) => {
      if (response) {
        showUploadResult(response, file);
      }
      return file.previewElement.classList.add("dz-success");
    });
    this.on("error", (file, response) => {
      if (response) {
        showUploadResult(response, file);
      }
      return file.previewElement.classList.add("dz-error");
    });
    this.on("complete", (file) => {
      this.removeFile(file);
    });
  }      
};

</script>
{% endblock %}

datadoc/templates/datadoc/partials/templates.html
<h5>Templates</h5>
<div class="btn-group-vertical" role="group" style="display: flex;">
  <a class="btn btn-outline-secondary"
     href="{% url 'datadoc:download_template' 'template.csv' %}" download>
    Download Excel Template</a>
  <a class="btn btn-outline-secondary"
     href="{% url 'datadoc:download_template' 'template.json' %}" download>
    Download JSON-LD Template</a>
  <a class="btn btn-outline-secondary"
     href="{% url 'datadoc:download_template' 'template.yaml' %}" download>
    Download YAML Template</a>
</div>

datadoc/templates/datadoc/views/edit_form.html
{% extends datadoc_base_template %}

{% block content %}
<div class="container mt-4">
  <h3 class="mb-4">Documentation Form</h3>
  <div class="btn-toolbar" role="toolbar">
    <div class="btn-group btn-group-sm me-2" role="group">
      <button type="button" class="btn btn-secondary" onclick="addColumn()">
        Add column
      </button>
      <button type="button" class="btn btn-secondary" onclick="addRow()">
        Add row
      </button>
    </div>
    <div class="btn-group btn-group-sm me-2" role="group">
      <div class="btn-group btn-group-sm" role="group">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          Remove column
        </button>
        <ul class="dropdown-menu" id="remove-column"></ul>
      </div>
      <button type="button" class="btn btn-secondary" title="Remove the selected rows" onclick="deleteRows()">
        Remove rows
      </button>
    </div>
    <div class="btn-group btn-group-sm" role="group">
      <div class="btn-group btn-group-sm" role="group">
        <button id="btn-prefix" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
          aria-expanded="false">
          Prefix
        </button>
        <ul class="dropdown-menu" id="prefix">
          <li>
            <h6 class="dropdown-header">New prefix</h6>
          </li>
          <li><a class="dropdown-item" href="javascript:onAddPrefix()">Add</a></li>
          <li>
            <h6 class="dropdown-header">Remove prefix</h6>
          </li>
          {% for item in prefix_list %}
           <li><a class="dropdown-item" href="javascript:onRemovePrefix('{{ item.prefix }}')">{{ item.prefix }}: {{ item.iri }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="btn-group btn-group-sm me-2 ms-2" role="group">
      <button type="button" class="btn btn-secondary" onclick="viewPrefixes()">View Available Prefixes</button>
    </div>
    <div class="btn-group btn-group-sm  ms-auto" role="group">
      <button id="btn-copy" type="button" class="btn btn-light me-2 ms-2" onclick="copyCSV()">
        Copy CSV
      </button>
      <button id="btn-submit" type="button" class="btn btn-success" onclick="submitCSV()">
        Submit
      </button>
    </div>
  </div>
  <div class="modal fade" id="prefixModal" tabindex="-1" aria-labelledby="prefixModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="prefixModalLabel">Available Prefixes</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><b><i>
            If you don't find the required prefix below, please use Add from Prefix dropdown to set prefix's for
            your documentation.
          </i></b></p>
          <ul id="prefix-list" class="list-group">
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="warn-alert" class="alert alert-warning alert-dismissible fade show mt-2" role="alert" style="display:none">
    <span id="warn-message">Message</span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <div class="row" id="row-prefix" style="display: none;">
    <hr class="mt-3">
    <form class="row row-cols-lg-auto align-items-center">
      <div class="col-12">
        <label class="visually-hidden" for="inp-prefix">Prefix</label>
        <div class="input-group input-group-sm">
          <div class="input-group-text">Prefix</div>
          <input type="text" class="form-control" id="inp-prefix" placeholder="Enter prefix">
        </div>
      </div>
      <div class="col-12" style="padding-left: 0px;">
        <label class="visually-hidden" for="inp-iri">IRI</label>
        <div class="input-group input-group-sm">
          <div class="input-group-text">IRI</div>
          <input type="text" class="form-control" id="inp-iri" placeholder="Enter IRI">
        </div>
      </div>
      <div class="col-12" style="padding-left: 0px;">
        <button type="button" class="btn btn-light btn-sm" onclick="hidePrefix()">Cancel</button>
        <button type="button" class="btn btn-primary btn-sm" onclick="addPrefix()">Add prefix</button>
      </div>
      <div id="prefix-alert" class="col-12" style="padding-left: 0px;">
        <div id="prefix-alert-text" class="alert alert-danger" role="alert"
          style="padding-top: 4px; padding-bottom: 4px; margin-bottom: 0px">

        </div>
      </div>
    </form>
    <hr class="mt-3">
  </div>
  <table class="table table-bordered mt-2" id="dataTable">
    <thead></thead>
    <tbody></tbody>
  </table>
</div>
{% include 'datadoc/components/dialog.html' %}
{% endblock %}
{% block scripts %}
<script>
  var columns = [];
  var rows = [];
  var prefix = [];

  {% for item in prefix_list %}
  prefix.push({prefix: '{{ item.prefix }}', iri: '{{ item.iri }}'});
  {% endfor %}

  $(document).ready(function () {
    columns = ['@id', '@type'];
    rows = [['', '']];
    updateTable();
  });


  function showTooltip(col) {
    return col === '@id' ? 'The unique identifier of a resource.' : 'Ontology concept this resource belongs to.';
  }

  function showWarning(message) {
    $('#warn-message').text(message);
    $('#warn-alert').show();
  }
  function viewPrefixes() {
    fetch("{% url 'datadoc:get_prefixes' %}")
      .then(response => response.json())
      .then(data => {
        const list = document.getElementById('prefix-list');
        list.innerHTML = '';
        if (data.prefixes.length === 0) {
          list.innerHTML = '<li class="list-group-item text-muted">No prefixes available.</li>';
        } else {
          data.prefixes.forEach(p => {
            list.innerHTML += `<li class="list-group-item"><strong>${p.prefix}</strong>: ${p.iri}</li>`;
          });
        }
        new bootstrap.Modal(document.getElementById('prefixModal')).show();
      })
      .catch(err => {
        alert("Error fetching prefixes.");
      });
  }

  function generateUniqueId() {
    return 'id-' + Math.floor(Math.random() * 1000000);
  }

  function addColumn() {
    const columnName = "Column " + (columns.length + 1);
    columns.push(columnName);
    rows.forEach(row => {
      row.push('');
    });
    updateTable();
  }

  function addRow() {
    if (columns.length === 0) {
      showWarning("Please add at least one column before adding a row.");
      return;
    }
    let newRow = columns.map(col => '');
    rows.push(newRow);
    updateTable();
  }

  function getTextInput(value, onchange, readonly = false) {
    return `<input type="text" class="form-control form-control-sm" value="${value}" onchange="${onchange}" ${readonly ? 'readonly' : ''}>`;
  }

  function updateTable() {
    let header = '<tr><th></th>';
    $('#remove-column').empty();

    columns.forEach((col, colIndex) => {
      let tooltip = (col === '@id' || col === '@type') ? `data-bs-toggle="tooltip" title="${showTooltip(col)}"` : '';
      let onchange = (col !== '@id' && col !== '@type') ? `renameColumn(${colIndex}, this.value)` : '';
      let readonly = (col === '@id' || col === '@type');
      header += `<th ${tooltip}>${getTextInput(col, onchange, readonly)}</th>`;

      if (!readonly) {
        $('#remove-column').append(`<li><a class="dropdown-item" href="javascript:deleteColumn(${colIndex})">${col}</a></li>`);
      }
    });
    header += '</tr>';
    $('#dataTable thead').html(header);

    let bodyHtml = '';
    rows.forEach((row, rowIndex) => {
      bodyHtml += `<tr><td><input class="form-check-input" type="checkbox" id="row-${rowIndex}"></td>`;
      columns.forEach((col, colIndex) => {
        bodyHtml += `<td><input type="text" class="form-control form-control-sm" value="${row[colIndex]}" onchange="updateRowValue(${rowIndex}, ${colIndex}, this.value)"></td>`;
      });
      bodyHtml += '</tr>';
    });
    $('#dataTable tbody').html(bodyHtml);


    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    tooltipTriggerList.forEach(function (tooltipTriggerEl) {
      new bootstrap.Tooltip(tooltipTriggerEl)
    });

  }

  function renameColumn(colIndex, newName) {
    columns[colIndex] = newName;
    updateTable();
  }

  function deleteColumn(colIndex) {
    if (columns[colIndex] === '@id' || columns[colIndex] === '@type') {
      showWarning("Cannot delete the '@id' or '@type' columns.");
      return;
    }
    columns.splice(colIndex, 1);
    rows.forEach(row => row.splice(colIndex, 1));
    updateTable();
  }

  function deleteRows() {
    let remove = $('input[id^="row-"]:checked').map((i, inp) => Number(inp.id.substring(4))).toArray();
    rows = rows.filter((_, i) => !remove.includes(i));
    updateTable();
  }

  function updateRowValue(rowIndex, colIndex, newValue) {
    rows[rowIndex][colIndex] = newValue;
  }

  function validateTable() {
    let valid = true;
    if (columns.length === 0 || rows.length === 0) {
      showWarning("Please add some columns and rows first!");
      valid = false;
    } else {
      for (let i = 0; i < rows.length; i++) {
        for (let j = 0; j < columns.length; j++) {
          if (!rows[i][j]) {
            showWarning("Please fill in all fields before saving the CSV.");
            valid = false;
            break;
          }
        }
      }
    }
    if (valid) {
      $('#warn-alert').hide();
    }
    return valid;
  }

  function generateCSV() {
    let csvContent = '';
    if (validateTable()) {
      csvContent = columns.join(",") + "\n";
      rows.forEach(row => {
        csvContent += row.join(",") + "\n";
      });
    }
    return csvContent;
  }

  function copyCSV() {
    navigator.clipboard.writeText(generateCSV());
  }

  function submitCSV() {
    let csvContent = generateCSV();
    if (csvContent) {
      let csv_prefix = "";
      prefix.forEach(p => {
        csv_prefix += `${p.prefix}:${p.iri}\n`;
      });
      console.log(csv_prefix);
      fetch('{% url "datadoc:process_csv" %}', {
        method: 'POST',
        headers: {
          'HX-Request': 'true',
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: `csv_data=${encodeURIComponent(csvContent)}&csv_prefix=${encodeURIComponent(csv_prefix)}`
      })
        .then(response => response.json())
        .then(data => {
          showDialog(data.message, data.status_code);
          if (Number(data.status_code) === 200) {
            columns = ['@id', '@type'];
            rows = [['', '']];
            updateTable();
            $('#warn-alert').hide();
          }
        });
    }
  }

  function onAddPrefix() {
    $('#inp-prefix').val('');
    $('#inp-iri').val('');
    $('#prefix-alert').hide();
    $('#row-prefix').show();
  }

  function addPrefix() {
    let error = '';
    let iri = $('#inp-iri').val();
    if (!iri) {
      error = 'Prefix IRI is empty!';
    }
    let name = $('#inp-prefix').val();
    if (!name) {
      error = 'Prefix name is empty!'
    } else {
      let found = prefix.find(x => x.prefix == name);
      if (found) {
        error = `Prefix "${name}" already exists!`;
      }
    }
    if (error) {
      $('#prefix-alert-text').text(error);
      $('#prefix-alert').show();
    } else {
      $('#prefix-alert').hide();
      let item = {
        prefix: $('#inp-prefix').val(),
        iri: $('#inp-iri').val()
      };
      prefix.push(item);
      let href = `javascript:onRemovePrefix('${item.prefix}')`;
      let label = `${item.prefix}: ${item.iri}`;
      $('#prefix').append(`<li><a class="dropdown-item" href="${href}">${label}</a></li>`);
      $('#row-prefix').hide();
    }
  }

  function hidePrefix() {
    $('#row-prefix').hide();
  }

  function onRemovePrefix(name) {
    prefix = prefix.filter(x => x.prefix != name);
    let menu = '';
    menu += '<li><h6 class="dropdown-header">New prefix</h6></li>';
    menu += '<li><a class="dropdown-item" href="javascript:onAddPrefix()">Add</a></li>';
    menu += '<li><h6 class="dropdown-header">Remove prefix</h6></li>';
    prefix.forEach(item => {
      let href = `javascript:onRemovePrefix('${item.prefix}')`;
      let label = `${item.prefix}: ${item.iri}`;
      menu += `<li><a class="dropdown-item" href="${href}">${label}</a></li>`;
    });
    $('#prefix').empty().append(menu);
  }

</script>
{% endblock %}

datadoc/templates/datadoc/views/upload_url.html
{% extends datadoc_base_template %}

{% block content %}
<div class="container mt-4">
  <div class="alert alert-info" role="alert">
    <p>
      Please provide a valid download URL to the data documentation file
      (e.g., "http://example.com/file"). The file should serve structured
      documentation and can be publicly accessible or private (with appropriate
      authentication).
    </p>
    <hr>
    <p class="mb-0">
      Accepted file types include CSV, JSON, YAML, and their respective variations.
      Example templates can be found
      <a href="{% url 'datadoc:upload_file' %}" target="_blank">here</a>
    </p>
  </div>
  <form id="url-form" method="post" hx-post="{% url 'datadoc:upload_file_url' %}" hx-target="#processing"
        hx-swap="innerHTML">
    {% csrf_token %}
    <div class="input-group mb-3">
      <input id="url" name="url" type="text" class="form-control"
             placeholder="Paste file accesss URL here">
      <button class="btn btn-success" type="submit" id="btn-submit" disabled>Submit</button>
    </div>
  </form>
  <div id="processing" class="alert alert-warning" role="alert" style="display: none;">
    Processing request for documentation... Please wait..
  </div>
</div>

{% include 'datadoc/components/dialog.html' %}
{% endblock %}
{% block scripts %}
{{ block.super }}
<script>
  document.getElementById('url').addEventListener('input', function () {
      document.getElementById('btn-submit').disabled = !this.value;
  });

  document.addEventListener('htmx:beforeRequest', function () {
    $('#processing').show();
  });

  document.addEventListener('htmx:afterRequest', function (event) {
    const response = JSON.parse(event.detail.xhr.responseText);
    $('#processing').hide();
    showDialog(response.message, response.status_code);
  });
</script>
{% endblock %}